### ISSUE TITLE
Issues with [route]?

### ISSUE THREAD

**Issue by possan** [Wasted-Audio/hvcc#237]
Maybe i'm going about this in the wrong way, but i'm trying to parse incoming messages created in the c code and then use route to route on a number but i noticed that the switchcase code generated tries to match on the hash of the number instead of the number itself.

This simple example shows the problem:
![Screenshot 2024-12-27 at 23 08 04](https://github.com/user-attachments/assets/bd601bd4-7a56-4cae-928b-53fc7ed0ddf1)

The generated message code looks like this:
```c
msg_init(m, 2, msg_getTimestamp(n));
msg_setFloat(m, 0, 42.0f);
msg_setSymbol(m, 1, "world");
cSwitchcase_fuKeOpcQ_onMessage(_c, NULL, 0, m, NULL);
```

The generated switch code (in `cSwitchcase_fuKeOpcQ_onMessage`) looks like this:
```c
switch (msg_getHash(m, msgIndex)) {
  case 0x42280000: { // "42.0"
    cSlice_onMessage(_c, &Context(_c)->cSlice_K2FFGYrJ, 0, m, &cSlice_K2FFGYrJ_sendMessage);
    break;
  }
  default: {
    break;
  }
}
```

**Comment by dromer** [comment]
But what is the issue exactly? The `msg_getHash()` function turns whatever was this first element into a hashed object which will match `42.0`.

I don't see any "issue" with the resulting code other than that because of the switch/case we cannot set the route arguments dynamically, which is its main limitation.

Your example works for me and the messages gets routed correctly (although print omits the `hello` in the output).

**Comment by dromer** [comment]
This works correctly for me:

![2024-12-28_09-48](https://github.com/user-attachments/assets/4fbb7a41-55b8-450f-9a6b-b363feeafaed)

**Comment by possan** [comment]
hmm, just tried the issue in a smaller test setup and indeed it seems to do the correct thing!

wonder why it failed in the other set, oh well...

**Comment by dromer** [comment]
If you manage to reproduce then please share a minimal patch that showcases the specific issue :)
